"""
SUPERNATURAL - Class Session Model
Tracks every autonomous class session with Google Meet link
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Boolean, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class ClassSession(Base):
    __tablename__ = "class_sessions"

    id              = Column(Integer, primary_key=True, index=True)
    mentor_id       = Column(Integer, ForeignKey("mentors.id"))
    title           = Column(String, nullable=False)
    subject         = Column(String, nullable=False)
    description     = Column(Text, nullable=True)

    # ── Scheduling ─────────────────────────────────────────────────────────
    scheduled_at    = Column(DateTime(timezone=True), nullable=False)
    duration_minutes = Column(Integer, default=60)
    is_recurring    = Column(Boolean, default=True)

    # ── Google Meet ────────────────────────────────────────────────────────
    meet_link       = Column(String, nullable=True)   # Auto-generated by N8N
    calendar_event_id = Column(String, nullable=True)

    # ── Status ─────────────────────────────────────────────────────────────
    is_email_sent   = Column(Boolean, default=False)
    is_quiz_generated = Column(Boolean, default=False)
    attendees       = Column(JSON, default=[])         # list of student emails

    # ── Timestamps ─────────────────────────────────────────────────────────
    created_at      = Column(DateTime(timezone=True), server_default=func.now())

    # ── Relationships ──────────────────────────────────────────────────────
    mentor  = relationship("Mentor", back_populates="sessions")
    quizzes = relationship("Quiz",   back_populates="session")

